package com.example.fakebook.global.exception;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;

@Getter
@RequiredArgsConstructor
public enum CommonException implements ExceptionType {
    COMMON_UNKNOWN_EXCEPTION(HttpStatus.INTERNAL_SERVER_ERROR),
    COMMON_INVALID_INPUT_EXCEPTION(HttpStatus.BAD_REQUEST),
    COMMON_NOT_FOUND_EXCEPTION(HttpStatus.NOT_FOUND),
    COMMON_UNAUTHORIZED_EXCEPTION(HttpStatus.UNAUTHORIZED),

    DB_UNKNOWN_EXCEPTION(HttpStatus.INTERNAL_SERVER_ERROR),
    DB_NOT_FOUND_EXCEPTION(HttpStatus.NOT_FOUND),
    DB_ALREADY_EXIST_EXCEPTION(HttpStatus.CONFLICT),
    DB_ALREADY_DELETED_EXCEPTION(HttpStatus.NOT_MODIFIED),

    TOKEN_UNKNOWN_EXCEPTION(HttpStatus.INTERNAL_SERVER_ERROR),
    TOKEN_UNAUTHORIZED_EXCEPTION(HttpStatus.UNAUTHORIZED),
    TOKEN_CREATION_EXCEPTION(HttpStatus.INTERNAL_SERVER_ERROR),
    TOKEN_INVALID_EXCEPTION(HttpStatus.BAD_REQUEST),
    TOKEN_NOT_FOUND_EXCEPTION(HttpStatus.NOT_FOUND),
    TOKEN_EXPIRED_EXCEPTION(HttpStatus.BAD_REQUEST),

    CRYPTO_UNKNOWN_EXCEPTION(HttpStatus.INTERNAL_SERVER_ERROR),
    CRYPTO_ENCRYPTION_FAIL_EXCEPTION(HttpStatus.INTERNAL_SERVER_ERROR),

    CHAT_UNKNOWN_EXCEPTION(HttpStatus.INTERNAL_SERVER_ERROR),
    CHAT_CHANNEL_NOT_FOUND_EXCEPTION(HttpStatus.NOT_FOUND),
    CHAT_CANNOT_SEND_MESSAGE(HttpStatus.BAD_REQUEST),
    CHAT_UNAUTHORIZED_EXCEPTION(HttpStatus.UNAUTHORIZED),

    REFLECTION_UNKNOWN_EXCEPTION(HttpStatus.INTERNAL_SERVER_ERROR),
    REFLECTION_FIELD_NOT_FOUND_EXCEPTION(HttpStatus.NOT_FOUND)
    ;

    private final HttpStatus httpStatus;
    @Override
    public String getName(){
        return this.name();
    }
}