package com.example.fakebook.global.exception;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum CommonException implements ExceptionType {
    // GLOBAL
    GLOBAL_UNKNOWN_EXCEPTION("000-000", "GLOBAL_UNKNOWN_EXCEPTION"),
    GLOBAL_INVALID_INPUT("000-001", "GLOBAL_INVALID_INPUT"),
    GLOBAL_NOT_FOUND("000-002", "GLOBAL_NOT_FOUND"),

    // DB
    DB_UNKNOWN_EXCEPTION("001-000", "DB_UNKNOWN_EXCEPTION"),
    DB_NOT_FOUND_EXCEPTION("001-001", "DB_NOT_FOUND_EXCEPTION"),
    DB_ALREADY_EXIST_EXCEPTION("001-002", "DB_ALREADY_EXIST_EXCEPTION"),
    DB_ALREADY_DELETED_EXCEPTION("001-003", "DB_ALREADY_DELETED_EXCEPTION"),

    // TOKEN
    TOKEN_UNKNOWN_EXCEPTION("002-000", "TOKEN_UNKNOWN_EXCEPTION"),
    TOKEN_UNAUTHORIZED_EXCEPTION("002-001", "TOKEN_UNAUTHORIZED_EXCEPTION"),
    TOKEN_CREATION_EXCEPTION("002-002", "TOKEN_CREATION_EXCEPTION"),
    TOKEN_INVALID_EXCEPTION("002-003", "TOKEN_INVALID_EXCEPTION"),
    TOKEN_NOT_FOUND_EXCEPTION("002-004", "TOKEN_NOT_FOUND_EXCEPTION"),
    TOKEN_EXPIRED_EXCEPTION("002-005", "TOKEN_EXPIRED_EXCEPTION"),

    // CRYPTO
    CRYPTO_UNKNOWN_EXCEPTION("003-000", "CRYPTO_UNKNOWN_EXCEPTION"),
    CRYPTO_ENCRYPTION_FAIL_EXCEPTION("003-001", "CRYPTO_ENCRYPTION_FAIL_EXCEPTION"),

    // CHAT
    CHAT_UNKNOWN_EXCEPTION("004-000", "CHAT_UNKNOWN_EXCEPTION"),
    CHAT_CHANNEL_ID_NOT_FOUND_EXCEPTION("004-001", "CHAT_CHANNEL_ID_NOT_FOUND_EXCEPTION"),
    CHAT_UNAUTHORIZED_EXCEPTION("004-002", "CHAT_UNAUTHORIZED_EXCEPTION");

    private final String status;
    private final String message;
}